version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build:
          context: jfrog-pipelines-sample

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run: |
          pip install requests -i http://${DOCKER_REGISTRY_LOGIN}:${ARTIFACTORY_API_KEY}@${DOCKER_REGISTRY}/artifactory/api/pypi/jerome-python-dev/simple --trusted-host ${DOCKER_REGISTRY}
      - run: |
          python main.py
